mlp:
  discover: "**.text_model.encoder.layers.*.mlp"
  slots:
    up: "fc1"    # 768 -> 3072
    down: "fc2"    # 3072 -> 768

norms:
  discover: "**.text_model.encoder.layers.*"
  slots:
    pre_norm:  "layer_norm1"
    post_norm: "layer_norm2"

attn:
  discover: "**.text_model.encoder.layers.*.self_attn"
  slots:
    q: "q_proj"   # 768 -> 768*3
    k: "k_proj"  # 768 -> 768   
    v: "v_proj"  # 768 -> 768
    out: "out_proj"  # 768 -> 768 