encoders:
  text.0:                 
    embed:                                  # for CLIP, this is the text embedding layer   
    blocks.0:                               # for CLIP, this is the first transformer block
      attn
        k|q|v|z|attn_out(after softmax)     # for attention blocks, specify the sub-sub-blocks
      mlp.0|mlp.1|mlp.2|...                 # for feed-forward blocks, specify the linear layers
  text.1:                                   # optional (e.g., SDXL has an additional text encoder)

  image.0:                                  # for SD, this inclueds the VAE block 
  image.1:                                  # in case there are multiple encoders 

denoisers:
  0:                                        # for each timestep, specify the denoiser block
    up|down|mid|None:                       # e.g., DiT it can be none
      - attn1|attn2|...:                    # for each block, specify the sub-blocks
        - k|q|v|z|attn_out(after softmax)   # for attention blocks, specify the sub-sub-blocks
        - mlp.0|mlp.1|mlp.2|...             # for feed-forward blocks, specify the linear layers
      - conv1|conv2|conv3|...               # for conv blocks, specify the conv layers