version: 1

# You can put shared defaults here
common:
  dataset: "nirmalendu01/socialcounterfactuals-200"
  val_split: "validation"
  run_name: "steer_mlp_train"
  d_submodule: 4096*320                      # equals INPUT_DIM
  dataset_column: "caption"
  ground_truth_column: ["race", "gender"]
  training_device: "cuda:0"
  data_device: "cpu"
  autocast_dtype: "bfloat16"
  outputs_root: "runs"
  wandb_config: "reporting/config.yaml"
  gt_processing_fn: "scripts.train_pipeline:gt_processing_fn"
  mapper: "twohead_mlp"
  mapper_kwargs:
    input_dim: ((4096*320))
    hidden_dim: 4096
    output_dims: [7, 2]
  loss: "torch.nn.CrossEntropyLoss"
  optimizer:
    name: "torch.optim.Adam"
    kwargs:
      lr: 1.0e-5
  flags:
    use_memmap: true
    cache_activations: true
  training:
    train_steps: 30
    refresh_batch_size: 64
    out_batch_size: 32
    subset: 100
    denoiser_steps: [10]       

# You can define one or more experiment blocks. Each runs over its accessor_grid.
experiments:
  - name: "sdxl_unet_2_down_blocks"
    accessor_grid:
      - "model.unet_2.down_attn_blocks[0].self_attn_out"
      - "model.unet_2.down_attn_blocks[0].cross_attn_out"
      - "model.unet_2.down_attn_blocks[1].self_attn_out"
      - "model.unet_2.down_attn_blocks[1].cross_attn_out"
      - "model.unet_2.down_attn_blocks[2].self_attn_out"
      - "model.unet_2.down_attn_blocks[2].cross_attn_out"
      - "model.unet_2.down_attn_blocks[3].self_attn_out"
      - "model.unet_2.down_attn_blocks[3].cross_attn_out"
      - "model.unet_2.down_attn_blocks[4].self_attn_out"
      - "model.unet_2.down_attn_blocks[4].cross_attn_out"
      - "model.unet_2.down_attn_blocks[5].self_attn_out"
      - "model.unet_2.down_attn_blocks[5].cross_attn_out"
